### PR TITLE
DRAFT: Add test archlinux iso

### PR DESCRIPTION
**Pull request by wcampbell0x2a**
~~This is a `707M` bytes image that doesn't unsquashfs that fast... at all.~~

### CODE REVIEW

**Comment by wcampbell0x2a** [comment]
> This is a `707M` bytes image that doesn't unsquashfs that fast... at all.

Fixed the speed with https://github.com/wcampbell0x2a/squashfs-deku/pull/35, still working on correctness!

**Comment by wcampbell0x2a** [comment]
Error one:
```
thread 'test_archlinux_iso_rootfs' panicked at 'called `Result::unwrap()` on an `Err` value: StdIo(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', /home/wcampbell/projects/wcampbell/backhand/src/squashfs.rs:283:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test_archlinux_iso_rootfs ... FAILED
```

Error two:
```
$ unsquashfs test-assets/test_archlinux_iso_rootfs/bytes.squashfs
read_fragment_table: Bad fragment count in super block
FATAL ERROR: File system corruption detected
```

**Comment by rbran** [comment]
In the latest version this takes around 45s.

**Comment by rbran** [comment]
I'll investigate, but I remember that total size was calculated using raw cast (I think as u32) and possibility overflowing, as a sanity check I made that try into.

**Comment by wcampbell0x2a** [comment]
Yah I think this is correct, as it's a limitation of SquashFS itself?

I'm not at my computer, is that error in the image we generate, or in the iso image?

**Comment by wcampbell0x2a** [comment]
Ah yes you're correct.

I really should replace the `as T` statements with try_from and from...

**Comment by wcampbell0x2a** [comment]
> The error is in backhand code that generate a new image. It's able to parse the image, it's just unable to create a new one.
> 
> In `v.0.11.0` the same thing happened, but because there was not explicit `try_into().unwrap()` it just overflow the `total_size`.
> 
> BTW: you can reproduce this bug with a much simpler file:
> 
> ```shell
> mkdir many_files
> for i in {0..18000}; do touch many_files/$i; done
> mksquashfs many_files/ many_files.squashfs
> rm -rf many_files
> ```
> 
> You can then reproduce this error using:
> 
> ```rust
> touch 18001
> add many_files.squashfs 18001 /
> ```

I need to add tests, but https://github.com/wcampbell0x2a/backhand/pull/213 should fix this.

**Comment by wcampbell0x2a** [comment]
@rbran if you apply both #215 and #213, the following errors shows up. Trying to call `extract_dir` on a `BasicFile`. Looks like on the `src` dir.
```
thread 'test_archlinux_iso_rootfs' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedInode(BasicFile(BasicFile { blocks_start: 0, frag_index: 512, block_offset: 71048, file_size: 8871, block_sizes: [] }))', tests/test.rs:53:91
```

https://github.com/wcampbell0x2a/backhand/blob/1f00845a298a5f01396b71ffd293e04e960a8b08/src/squashfs.rs#L538

**Comment by rbran** [comment]
I'll investigate this, but calling `extract_dir` into a non-directory inode is invalid. Whatever is calling this function, is causing this panic.

**Comment by wcampbell0x2a** [comment]
> I'll investigate this, but calling `extract_dir` into a non-directory inode is invalid. Whatever is calling this function, is causing this panic.

Certainly. Something must be off with the writer.

**Comment by rbran** [comment]
I could find time this morning to test this, unfortunately I was not able to fix it yet.

But I found a much fast test: [test_few_dirs_many_files](https://github.com/rbran/backhand/commits/big-files). I send those files to your email.

The problem seems to be in the creation of a new squashfs file, the files inside the extend directory seems to be lost.

**Comment by wcampbell0x2a** [comment]
Pushed a couple of commits to a branch of your branch: https://github.com/wcampbell0x2a/backhand/commits/big-files-w

- Further fixed fragment tables
- Fixed InodeId in DirEntry

Still getting that error, but more correct for these large images.

**Comment by wcampbell0x2a** [comment]
Mostly good news, with the following line commented out all tests pass. 

https://github.com/wcampbell0x2a/backhand/blob/d243dd6bbeb208bb5eac6953ed433d230ba547cb/tests/test.rs#L53

This means that while our reader fails, the generated `bytes.image` file is a valid SquashFS image.

**Comment by wcampbell0x2a** [comment]
The error comes from a zero-sized dir existing?
```
2023-04-20T03:38:19.210069Z DEBUG into_filesystem_reader:extract_dir:extract_dir:extract_dir: backhand::squashfs: /usr/src
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedInode(BasicFile(BasicFile { blocks_start: 0, frag_index: 512, block_offset: 71048, file_size: 8871, block_sizes: [] }))', src/bin/unsquashfs.rs:83:60
$ ls -lah squashfs-root/usr/
total 8.0K
drwxr-xr-x 1 wcampbell wcampbell   76 Mar  1 07:52 ./
drwxr-xr-x 1 wcampbell wcampbell  136 Mar  1 07:52 ../
drwxr-xr-x 1 wcampbell wcampbell  40K Mar  1 07:52 bin/
drwxr-xr-x 1 wcampbell wcampbell  10K Mar  1 07:52 include/
drwxr-xr-x 1 wcampbell wcampbell  42K Mar  1 07:52 lib/
lrwxrwxrwx 1 wcampbell wcampbell    3 Jan 31 15:51 lib64 -> lib/
drwxr-xr-x 1 wcampbell wcampbell   72 Mar  1 07:52 local/
drwxr-xr-x 1 wcampbell wcampbell    8 Mar  1 07:52 man/
lrwxrwxrwx 1 wcampbell wcampbell    3 Jan 31 15:51 sbin -> bin/
drwxr-xr-x 1 wcampbell wcampbell 1.5K Mar  1 07:52 share/
drwxr-xr-x 1 wcampbell wcampbell    0 Jan 31 15:51 src/
```

**Comment by rbran** [comment]
> The error comes from a zero-sized dir existing?

I would imagine some kind of overflow is happening, and the wrong inode is being read, in this case, a file instead of a directory.

**Pull request closed without merging**
