### PR TITLE
bins: Fix macOS builds

### LINKED ISSUE #235: OSX Cargo Output.
Cargo output below. I believe this is due to various types on BSD derivatives such as MacOS/OSX being different sizes to those on Linux.

Not a huge issue for me personally (prefer to use Linux, just had a Mac on hand). 

```
   Compiling backhand v0.12.0
error[E0308]: mismatched types
   --> /Users/lol/.cargo/registry/src/github.com-1ecc6299db9ec823/backhand-0.12.0/src/bin/unsquashfs.rs:324:41
    |
324 |                         Mode::from_bits(u32::from(node.header.permissions)).unwrap(),
    |                         --------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u16`, found `u32`
    |                         |
    |                         arguments to this function are incorrect
    |
note: associated function defined here
   --> /Users/lol/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.26.2/src/sys/stat.rs:33:1
    |
33  | / libc_bitflags! {
34  | |     /// "File mode / permissions" flags.
35  | |     pub struct Mode: mode_t {
36  | |         /// Read, write and execute for owner.
...   |
65  | |     }
66  | | }
    | |_^
    = note: this error originates in the macro `__impl_bitflags` which comes from the expansion of the macro `libc_bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /Users/lol/.cargo/registry/src/github.com-1ecc6299db9ec823/backhand-0.12.0/src/bin/unsquashfs.rs:325:25
    |
321 |                     match mknod(
    |                           ----- arguments to this function are incorrect
...
325 |                         u64::from(*device_number),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
    |
note: function defined here
   --> /Users/rlol/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.26.2/src/sys/stat.rs:173:8
    |
173 | pub fn mknod<P: ?Sized + NixPath>(
    |        ^^^^^

error[E0308]: mismatched types
   --> /Users/lol/.cargo/registry/src/github.com-1ecc6299db9ec823/backhand-0.12.0/src/bin/unsquashfs.rs:355:37
    |
355 |                     Mode::from_bits(u32::from(node.header.permissions)).unwrap(),
    |                     --------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u16`, found `u32`
    |                     |
    |                     arguments to this function are incorrect
    |
note: associated function defined here
   --> /Users/lol/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.26.2/src/sys/stat.rs:33:1
    |
33  | / libc_bitflags! {
34  | |     /// "File mode / permissions" flags.
35  | |     pub struct Mode: mode_t {
36  | |         /// Read, write and execute for owner.
...   |
65  | |     }
66  | | }
    | |_^
    = note: this error originates in the macro `__impl_bitflags` which comes from the expansion of the macro `libc_bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /Users/lol/.cargo/registry/src/github.com-1ecc6299db9ec823/backhand-0.12.0/src/bin/unsquashfs.rs:356:21
    |
352 |                 match mknod(
    |                       ----- arguments to this function are incorrect
...
356 |                     u64::from(*device_number),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
    |
note: function defined here
   --> /Users/lol/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.26.2/src/sys/stat.rs:173:8
    |
173 | pub fn mknod<P: ?Sized + NixPath>(
    |        ^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `backhand` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `backhand v0.12.0`, intermediate artifacts can be found at `/var/folders/f6/gkxjd1g111x5b13kvfzm2db40000gn/T/cargo-installepyyvn`

$ cargo version
cargo 1.69.0 (6e9a83356 2023-04-12)
```

This comment was enlightening about how some types are different: https://github.com/tikv/tikv/issues/4130#issuecomment-457918524

### PR DESCRIPTION
**Pull request by wcampbell0x2a**
Closes #235

### CODE REVIEW

**Comment by wcampbell0x2a** [comment]
hey @fullspectrumdev could you check if this fixes https://github.com/wcampbell0x2a/backhand/issues/235 ?

**Comment by fullspectrumdev** [comment]
Still some errors (similar to before) after applying this - seems the types are real picky across various platforms:

```
error[E0308]: mismatched types
   --> src/bin/unsquashfs.rs:412:25
    |
408 |                     match mknod(
    |                           ----- arguments to this function are incorrect
...
412 |                         u64::from(*device_number),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
    |
note: function defined here
   --> /Users/darren/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.2/src/sys/stat.rs:173:8
    |
173 | pub fn mknod<P: ?Sized + NixPath>(
    |        ^^^^^

error[E0308]: mismatched types
   --> src/bin/unsquashfs.rs:443:21
    |
439 |                 match mknod(
    |                       ----- arguments to this function are incorrect
...
443 |                     u64::from(*device_number),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
    |
note: function defined here
   --> /Users/darren/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.2/src/sys/stat.rs:173:8
    |
173 | pub fn mknod<P: ?Sized + NixPath>(
    |        ^^^^^

For more information about this error, try `rustc --explain E0308`.

```

Apologies for the delay, took me a bit to get back into my github.

**Comment by Dr-Emann** [comment]
Looks like on macos (which I also have) `dev_t` is an `i32`. I think it might need to use `as`, since there's no way to cast from `u32` to `i32` with `From::from`

**Comment by wcampbell0x2a** [comment]
Could you try current `master`? I think https://github.com/wcampbell0x2a/backhand/pull/259 should have fixed these issues.

**Comment by fullspectrumdev** [comment]
Just pulled from master.

```
% git log --pretty=format:'%h' -n 1

2c53a1f

% git branch
* master

% cargo build

< snipped heavily all the irrelevant output >

   Compiling backhand v0.13.0 (/private/tmp/backhand)
error[E0277]: the trait bound `i32: From<u32>` is not satisfied
   --> src/bin/unsquashfs.rs:412:37
    |
412 |                         dev_t::from(*device_number),
    |                         ----------- ^^^^^^^^^^^^^^ the trait `From<u32>` is not implemented for `i32`
    |                         |
    |                         required by a bound introduced by this call
    |
    = help: the following other types implement trait `From<T>`:
              <i32 as From<NonZeroI32>>
              <i32 as From<bool>>
              <i32 as From<errno::Errno>>
              <i32 as From<i16>>
              <i32 as From<i8>>
              <i32 as From<u16>>
              <i32 as From<u8>>

error[E0277]: the trait bound `i32: From<u32>` is not satisfied
   --> src/bin/unsquashfs.rs:443:33
    |
443 |                     dev_t::from(*device_number),
    |                     ----------- ^^^^^^^^^^^^^^ the trait `From<u32>` is not implemented for `i32`
    |                     |
    |                     required by a bound introduced by this call
    |
    = help: the following other types implement trait `From<T>`:
              <i32 as From<NonZeroI32>>
              <i32 as From<bool>>
              <i32 as From<errno::Errno>>
              <i32 as From<i16>>
              <i32 as From<i8>>
              <i32 as From<u16>>
              <i32 as From<u8>>

For more information about this error, try `rustc --explain E0277`.
error: could not compile `backhand` (bin "unsquashfs") due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by wcampbell0x2a** [comment]
@fullspectrumdev I pushed an update to this MR. I *think* that will build, don't know about testing it

**Comment by fullspectrumdev** [comment]
Sorry it took me so long to test this, but it now builds flawlessly on OSX. No warnings!

**Pull request merged**
