### PR TITLE
Use Read instead of Vec<u8> for files

### PR DESCRIPTION
**Pull request by rbran**

### CODE REVIEW

**Comment by wcampbell0x2a** [comment]
Fantastic! I opened https://github.com/wcampbell0x2a/backhand/pull/107 with some fixes that I saw, lmk what you think of the branch. Also added some benchmarks to confirm.

**Comment by rbran** [comment]
The only problem right now is the function `FilesystemReader::file` that returns a `Vec<u8>`, instead it should return an `impl Read`.

Other then that the lib will be ready to read huge file.

**Comment by rbran** [comment]
I think a good solution for that is to have something like this:

```rust
pub struct FilesystemFileReader<'a, R: SquashFsReader> {
    filesystem: &'a FilesystemReader<R>,
    file: &'a BasicFile,
    blocks_remaining: usize,
}

impl<'a, R: SquashFsReader> Read for FilesystemFileReader<'a, R> {
    fn read(&mut self, _buf: &mut [u8]) -> std::io::Result<usize> {
        todo!()
    }
}

impl<R: SquashFsReader> FilesystemReader<R> {
    /// From file details, extract FileBytes
    pub fn file<'a>(&'a self, basic_file: &'a BasicFile) -> FilesystemFileReader<'a, R> {
      todo!()
    }
  }
}
```

**Comment by rbran** [comment]
The #[cb8194b](https://github.com/wcampbell0x2a/backhand/pull/106/commits/cb8194bbf8be1c06ce1a94010a10eba7e945c8cc) implement interface.

**Pull request merged**
