### PR TITLE
Make TreeNode::insert error instead of panic

### PR DESCRIPTION
**Pull request by rbran**

### CODE REVIEW

**Comment by rbran** [comment]
Seems like `FilesystemWriter::push_file` have a bug that insert duplicated nodes. I'll try to fix this PR before taking it out of the draft.

**Comment by rbran** [comment]
https://github.com/wcampbell0x2a/backhand/blob/ab818b4b8c8911c57a135b9fbb8a06e60e3db7b8/src/filesystem/writer.rs#L270

This comparison is never true, because it compares left:`/a` with right:`a`.

**Comment by rbran** [comment]
The file `wcampbell.dev/squashfs/testing/test_raw_00/control.squashfs` is invalid, the files (including the root) have invalid permissions. Result of the directories being automatically created by `file_push`.

**Comment by rbran** [comment]
I removed the automatic directory creation on `push_dir` and `push_file` because it's problematic.

I was able to pass all tests locally, but the file `wcampbell.dev/squashfs/testing/test_raw_00/control.squashfs` is invalid, so it need to be updated so tests here pass.

**Comment by rbran** [comment]
This unfortunately breaks the API, because the `push_file` doc specify `This will make parent directories as needed with the same metadata of header`.

The functions `push_file` and `push_dir` are kind of awkward, I think they leave some open questions:
* What if the file/dir already exist?
* Path is auto created in `push_file`, but what about it in `push_dir`?
* Canonize (fix relative path like "a/../a/b") relative directories?

Let me know what do you think.

**Comment by wcampbell0x2a** [comment]
Looks good, nice find. I don't mind breaking changes.

> I was able to pass all tests locally, but the file wcampbell.dev/squashfs/testing/test_raw_00/control.squashfs is invalid, so it need to be updated so tests here pass.

The file should be small enough you can base64 it here and i'll put it on the host server.

> What if the file/dir already exist?

If the file already exists, I think this should be error and the image shouldn't be created. They should use `replace_file` for this. `remove_file` doesn't exists and should.

> Path is auto created in push_file, but what about it in push_dir?

I kinda think it should be the other way around, where `push_dir` acts like `mkdir -p` but `push_file` doesn't and errors if the folder wasn't created.

> Canonize (fix relative path like "a/../a/b") relative directories?

I didn't think I thought of this use case, but if it's tested and added in another MR I think it would be fine.

**Comment by rbran** [comment]
> The file should be small enough you can base64 it here and i'll put it on the host server.

I created the file using the command `mksquashfs this usr control.squashfs -mkfs-time 1666142775 -all-time 1666142775 -comp xz`, it seems to be reproducible, at least on the same machine.

BBS compatible file sharing command:
```bash
echo -n 'H4sICPLUJmQAA2NvbnRyb2wuc3F1YXNoZnMAyyguLOZgYGAwD/JPZmBgYmAEslkYBBkOAFksQPYDBgiwY4LQZlD6PxSsgckzQuh7UFoDqu6veVVEFAMDY6bSPTPmA4KNTIqMXCDxFIvF+x4A1XLGMrC/v8LAMPMkRH2E5M95DIyqjSDtHwV3b7Iz4O0GG8UYGTUBzbSIBqBpYMkeb/bfDxj+MwTEAp0tt8FfbYFEh8bxTM9bna02HI8ynfw3JRm+KxLp05gyJyxsRoN00eTpH7uqQ9ST51yvFM1LXSQ7w/jEyaqwdXNld7AqPVNqVArKO2b6nk2bJ8qAwfxQvQsDY04DyKKnyT3LkV3Ug+ai4KmMUBct22Cf/YBhCoN3LANDVn21YN6L24mOX86UPJgWt9V467FdOgwu2jOEcm27xa8aSH/rOT1r9r6TPz6fkt0f4PtD5btFb/NXc8+P8Uf6pn2bmPql/G7HiqrUc143GRiKt90SZGBMnwoKZiuVf+XIrhFoSIDGhg+UPgONDQe4jAOUVmBABQeg9AIo3QClYfH/DGoSS8MLZgYGAyaGUTAKRsEoGAWjYBSMglEwCkbBKBgFQwoAAPxLUcAAEAAA' | base64 -d | gzip -cd > control.squashfs
```

> If the file already exists, I think this should be error and the image shouldn't be created. They should use replace_file for this. remove_file doesn't exists and should.

This is the current behavior, but the error happen on the image creation, not on `push_file`/`push_dir` directly. I'll think in a way to fix that, but in a new PR, this is already too big.

> I kinda think it should be the other way around, where push_dir acts like mkdir -p but push_file doesn't and errors if the folder wasn't created.

I created a `push_dir_all` to be and `mkdir -p` and mirror the `std::fs::create_dir_all`. The `push_file` and `push_dir` don't create directories recursively.

**Pull request merged**
