### PR TITLE
Add Windows support for the lib

### PR DESCRIPTION
**Pull request by Wolfyxon**
I'm working on a tool that natively builds AppImages without `appimagetool` and I also need it to work under Windows.
This allows backhand to compile and work under Windows by not relying on unix specific modules.

### CODE REVIEW

**Comment by Wolfyxon** [comment]
I tested everything on both Windows and Linux.
Files are read and pushed without any issues.

**Comment by wcampbell0x2a** [comment]
Thanks! I'll make sure to check this out.

**Comment by wcampbell0x2a** [comment]
@Wolfyxon please run `cargo fmt`

**Comment by wcampbell0x2a** [comment]
Thanks!

**Pull request merged**
