### PR TITLE
Put nodes in single tree instead of a single vector

### PR DESCRIPTION
**Pull request by rbran**
There are some bugs that still need to figure out, but first I have some questions:

### CODE REVIEW

**Comment by rbran** [comment]
https://github.com/wcampbell0x2a/backhand/blob/d00cce14bd6075dbc2f9b4023a8fa6a11bfb5dee/tests/bin.rs#L16

How is this not breaking all your tests? All my tests are broken now :(

**Comment by rbran** [comment]
https://github.com/wcampbell0x2a/backhand/blob/d00cce14bd6075dbc2f9b4023a8fa6a11bfb5dee/tests/raw.rs#L77-L97

Are those values really static? This PR creates a slightly smaller file, but now this test fails, the output file seems valid tho

**Comment by rbran** [comment]
The https://github.com/wcampbell0x2a/backhand/pull/207/commits/3ae4ac3505a06895d667b47c4f5f171c735cda8d don't fix the `test_raw_00` test, I think that's because of the HashMap, that shuffle the directories, creating an output slightly different each execution.

I also need to remove the FilePhase2 from the public API.

**Comment by wcampbell0x2a** [comment]
> https://github.com/wcampbell0x2a/backhand/blob/d00cce14bd6075dbc2f9b4023a8fa6a11bfb5dee/tests/bin.rs#L16
> 
> How is this not breaking all your tests? All my tests are broken now :(

Probably a different version of `unsquashfs`, I think debian/ubuntu have an older version.

**Comment by wcampbell0x2a** [comment]
> The [3ae4ac3](https://github.com/wcampbell0x2a/backhand/commit/3ae4ac3505a06895d667b47c4f5f171c735cda8d) don't fix the `test_raw_00` test, I think that's because of the HashMap, that shuffle the directories, creating an output slightly different each execution.
> 
> I also need to remove the FilePhase2 from the public API.

I don't think we are reproducible right now (maybe we are?), But i more like the order to be deterministic if we can.

**Comment by wcampbell0x2a** [comment]
Hopefully you can rebase and https://github.com/wcampbell0x2a/backhand/pull/209 fixed the CI issue.

**Comment by rbran** [comment]
Is probably best for performance/memory usage to have a single vec with all nodes sorted by fullpath, but that may require more checks, I may do that in the future tho.

Anyways this PR simplify the process of creating a new SquashFs file by removing the NodeTree step, allowing `push_*` functions to return an error directly on call, instead of during the `write` call.

**Comment by wcampbell0x2a** [comment]
Thanks! lgtm

**Pull request merged**
